// Generated by @stylec/compiler. Do not edit.
import { __hash, __toDecl, type CSSProperties } from "@stylec/runtime";

export const cssHash = "ji6lkw";

const _tmpl = (h: string) => `.item_${h} {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
  background-color: #f9fafb;
  border-radius: 0.5rem;
  transition: background-color 0.15s;
}

.item_${h}:hover {
  background-color: #f3f4f6;
}

.left_${h} {
  display: flex;
  align-items: center;
}

.checkbox_${h} {
  height: 1.25rem;
  width: 1.25rem;
  margin-right: 0.75rem;
  accent-color: #3b82f6;
  border-radius: 0.25rem;
}

.checkbox_${h}:focus {
  outline: none;
  box-shadow: 0 0 0 2px #60a5fa;
}

.text_${h} {
  color: #1f2937;
}

.text_completed_${h} {
  text-decoration: line-through;
  color: #6b7280;
}

.delete_btn_${h} {
  color: #ef4444;
  background: none;
  border: none;
  cursor: pointer;
  transition: color 0.15s;
}

.delete_btn_${h}:hover {
  color: #b91c1c;
}
`;

export const css = _tmpl(cssHash);

export const classes = {
  item: "item_ji6lkw",
  left: "left_ji6lkw",
  checkbox: "checkbox_ji6lkw",
  text: "text_ji6lkw",
  text_completed: "text_completed_ji6lkw",
  delete_btn: "delete_btn_ji6lkw",
} as const;
export type ClassName = keyof typeof classes;
export default classes;

export function override(patch: Partial<Record<ClassName, CSSProperties>>) {
  const h = __hash(cssHash + JSON.stringify(patch));
  let extra = "";
  if (patch.item) extra += ".item_" + h + "{" + __toDecl(patch.item) + "}";
  if (patch.left) extra += ".left_" + h + "{" + __toDecl(patch.left) + "}";
  if (patch.checkbox)
    extra += ".checkbox_" + h + "{" + __toDecl(patch.checkbox) + "}";
  if (patch.text) extra += ".text_" + h + "{" + __toDecl(patch.text) + "}";
  if (patch.text_completed)
    extra +=
      ".text_completed_" + h + "{" + __toDecl(patch.text_completed) + "}";
  if (patch.delete_btn)
    extra += ".delete_btn_" + h + "{" + __toDecl(patch.delete_btn) + "}";
  const out = {
    item: "item_" + h,
    left: "left_" + h,
    checkbox: "checkbox_" + h,
    text: "text_" + h,
    text_completed: "text_completed_" + h,
    delete_btn: "delete_btn_" + h,
  };
  return { css: _tmpl(h) + extra, classes: out, cssHash: h };
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6WyJpdGVtIiwibGVmdCIsImNoZWNrYm94IiwidGV4dCIsInRleHRfY29tcGxldGVkIiwiZGVsZXRlX2J0biJdLCJzb3VyY2VzIjpbIlRvZG9JdGVtLnN0eWxlYy5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiLml0ZW0ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG4gIHBhZGRpbmc6IDAuNzVyZW07XG4gIG1hcmdpbi1ib3R0b206IDAuNXJlbTtcbiAgYmFja2dyb3VuZC1jb2xvcjogI2Y5ZmFmYjtcbiAgYm9yZGVyLXJhZGl1czogMC41cmVtO1xuICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kLWNvbG9yIDAuMTVzO1xufVxuXG4uaXRlbTpob3ZlciB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNmM2Y0ZjY7XG59XG5cbi5sZWZ0IHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbn1cblxuLmNoZWNrYm94IHtcbiAgaGVpZ2h0OiAxLjI1cmVtO1xuICB3aWR0aDogMS4yNXJlbTtcbiAgbWFyZ2luLXJpZ2h0OiAwLjc1cmVtO1xuICBhY2NlbnQtY29sb3I6ICMzYjgyZjY7XG4gIGJvcmRlci1yYWRpdXM6IDAuMjVyZW07XG59XG5cbi5jaGVja2JveDpmb2N1cyB7XG4gIG91dGxpbmU6IG5vbmU7XG4gIGJveC1zaGFkb3c6IDAgMCAwIDJweCAjNjBhNWZhO1xufVxuXG4udGV4dCB7XG4gIGNvbG9yOiAjMWYyOTM3O1xufVxuXG4udGV4dF9jb21wbGV0ZWQge1xuICB0ZXh0LWRlY29yYXRpb246IGxpbmUtdGhyb3VnaDtcbiAgY29sb3I6ICM2YjcyODA7XG59XG5cbi5kZWxldGVfYnRuIHtcbiAgY29sb3I6ICNlZjQ0NDQ7XG4gIGJhY2tncm91bmQ6IG5vbmU7XG4gIGJvcmRlcjogbm9uZTtcbiAgY3Vyc29yOiBwb2ludGVyO1xuICB0cmFuc2l0aW9uOiBjb2xvciAwLjE1cztcbn1cblxuLmRlbGV0ZV9idG46aG92ZXIge1xuICBjb2xvcjogI2I5MWMxYztcbn1cbiJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0VBQUNBO0VBZUFDO0VBS0FDO0VBYUFDO0VBSUFDO0VBS0FDOzs7Ozs7Ozs7Ozs7Ozs7SUExQ0FMO0lBZUFDO0lBS0FDO0lBYUFDO0lBSUFDO0lBS0FDIiwiaWdub3JlTGlzdCI6W119
