// Generated by @stylec/compiler. Do not edit.
import { __override, type CSSProperties } from "@stylec/runtime";

export const cssHash = "mwk3kw";

const _tmpl = (h: string) => `.item_${h} {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
  background-color: #f9fafb;
  border-radius: 0.5rem;
  transition: background-color 0.15s;
}

.item_${h}:hover {
  background-color: #f3f4f6;
}

.left_${h} {
  display: flex;
  align-items: center;
}

.checkbox_${h} {
  height: 1.25rem;
  width: 1.25rem;
  margin-right: 0.75rem;
  accent-color: #3b82f6;
  border-radius: 0.25rem;
}

.checkbox_${h}:focus {
  outline: none;
  box-shadow: 0 0 0 2px #60a5fa;
}

.text_${h} {
  color: #1f2937;
}

.text_completed_${h} {
  text-decoration: line-through;
  color: #6b7280;
}

.edit_input_${h} {
  flex: 1;
  min-width: 0;
  padding: 0.25rem 0.5rem;
  border: 1px solid #d1d5db;
  border-radius: 0.375rem;
  font-size: inherit;
  color: #1f2937;
}

.edit_input_${h}:focus {
  outline: none;
  border-color: #3b82f6;
}

.delete_btn_${h} {
  color: #ef4444;
  background: none;
  border: none;
  cursor: pointer;
  transition: color 0.15s;
}

.delete_btn_${h}:hover {
  color: #b91c1c;
}
`;

export const css = _tmpl(cssHash);

export const classes = {
  item: "item_mwk3kw",
  left: "left_mwk3kw",
  checkbox: "checkbox_mwk3kw",
  text: "text_mwk3kw",
  text_completed: "text_completed_mwk3kw",
  edit_input: "edit_input_mwk3kw",
  delete_btn: "delete_btn_mwk3kw",
} as const;
export type ClassName = keyof typeof classes;

export function override(patch: Partial<Record<ClassName, CSSProperties>>) {
  return __override(
    Object.keys(classes) as ClassName[],
    _tmpl,
    cssHash,
    patch
  ) as {
    css: string;
    classes: { [K in keyof typeof classes]: string };
    cssHash: string;
  };
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6WyJpdGVtIiwibGVmdCIsImNoZWNrYm94IiwidGV4dCIsInRleHRfY29tcGxldGVkIiwiZWRpdF9pbnB1dCIsImRlbGV0ZV9idG4iXSwic291cmNlcyI6WyJUb2RvSXRlbS5zdHlsZWMuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIi5pdGVtIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICBwYWRkaW5nOiAwLjc1cmVtO1xuICBtYXJnaW4tYm90dG9tOiAwLjVyZW07XG4gIGJhY2tncm91bmQtY29sb3I6ICNmOWZhZmI7XG4gIGJvcmRlci1yYWRpdXM6IDAuNXJlbTtcbiAgdHJhbnNpdGlvbjogYmFja2dyb3VuZC1jb2xvciAwLjE1cztcbn1cblxuLml0ZW06aG92ZXIge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjNmNGY2O1xufVxuXG4ubGVmdCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG5cbi5jaGVja2JveCB7XG4gIGhlaWdodDogMS4yNXJlbTtcbiAgd2lkdGg6IDEuMjVyZW07XG4gIG1hcmdpbi1yaWdodDogMC43NXJlbTtcbiAgYWNjZW50LWNvbG9yOiAjM2I4MmY2O1xuICBib3JkZXItcmFkaXVzOiAwLjI1cmVtO1xufVxuXG4uY2hlY2tib3g6Zm9jdXMge1xuICBvdXRsaW5lOiBub25lO1xuICBib3gtc2hhZG93OiAwIDAgMCAycHggIzYwYTVmYTtcbn1cblxuLnRleHQge1xuICBjb2xvcjogIzFmMjkzNztcbn1cblxuLnRleHRfY29tcGxldGVkIHtcbiAgdGV4dC1kZWNvcmF0aW9uOiBsaW5lLXRocm91Z2g7XG4gIGNvbG9yOiAjNmI3MjgwO1xufVxuXG4uZWRpdF9pbnB1dCB7XG4gIGZsZXg6IDE7XG4gIG1pbi13aWR0aDogMDtcbiAgcGFkZGluZzogMC4yNXJlbSAwLjVyZW07XG4gIGJvcmRlcjogMXB4IHNvbGlkICNkMWQ1ZGI7XG4gIGJvcmRlci1yYWRpdXM6IDAuMzc1cmVtO1xuICBmb250LXNpemU6IGluaGVyaXQ7XG4gIGNvbG9yOiAjMWYyOTM3O1xufVxuXG4uZWRpdF9pbnB1dDpmb2N1cyB7XG4gIG91dGxpbmU6IG5vbmU7XG4gIGJvcmRlci1jb2xvcjogIzNiODJmNjtcbn1cblxuLmRlbGV0ZV9idG4ge1xuICBjb2xvcjogI2VmNDQ0NDtcbiAgYmFja2dyb3VuZDogbm9uZTtcbiAgYm9yZGVyOiBub25lO1xuICBjdXJzb3I6IHBvaW50ZXI7XG4gIHRyYW5zaXRpb246IGNvbG9yIDAuMTVzO1xufVxuXG4uZGVsZXRlX2J0bjpob3ZlciB7XG4gIGNvbG9yOiAjYjkxYzFjO1xufVxuIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7RUFBQ0E7RUFlQUM7RUFLQUM7RUFhQUM7RUFJQUM7RUFLQUM7RUFlQUMiLCJpZ25vcmVMaXN0IjpbXX0=
